services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: test_my_sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Ptpl!234
      - MYSQL_DATABASE=aihackathon
      - MYSQL_USER=aiuser
      - MYSQL_PASSWORD=Ptpl!234
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --sql-mode=""
